package tests;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

import com.thoughtworks.selenium.Selenium;
import com.thoughtworks.selenium.webdriven.WebDriverBackedSelenium;

public class WebTests {
	private Selenium selenium;

	@Before
	public void setUp() throws Exception {
		WebDriver driver = new FirefoxDriver();
		String baseUrl = "http://localhost:4567/";
		selenium = new WebDriverBackedSelenium(driver, baseUrl);
	}

	@Test
	public void testWebTests() throws Exception {
		selenium.open("/");
		selenium.type("id=__username__", "Pavel");
		selenium.click("css=button.btn");
		selenium.waitForPageToLoad("30000");
		selenium.click("link=Relational Model");
		selenium.click("link=Attributes");
		selenium.waitForPageToLoad("30000");
		selenium.type("id=attribute", "A");
		selenium.click("css=button.btn");
		selenium.waitForPageToLoad("30000");
		selenium.type("id=attribute", "B");
		selenium.click("css=button.btn");
		selenium.waitForPageToLoad("30000");
		selenium.type("id=attribute", "C");
		selenium.click("css=button.btn");
		selenium.waitForPageToLoad("30000");
		selenium.type("id=attribute", "D");
		selenium.click("css=button.btn");
		selenium.waitForPageToLoad("30000");
		selenium.type("id=attribute", "E");
		selenium.click("css=button.btn");
		selenium.waitForPageToLoad("30000");
		selenium.click("link=Relational Model");
		selenium.click("link=Functional Dependencies");
		selenium.waitForPageToLoad("30000");
		selenium.click("Name=__ant__A");
		selenium.click("Name=__ant__B");
		selenium.click("Name=__ant__C");
		selenium.click("Name=__con__D");
		selenium.click("Name=__con__E");
		selenium.click("css=button.btn");
		selenium.waitForPageToLoad("30000");
		selenium.click("Name=__ant__A");
		selenium.click("Name=__ant__D");
		selenium.click("Name=__ant__E");
		selenium.click("Name=__con__B");
		selenium.click("css=button.btn");
		selenium.waitForPageToLoad("30000");
		selenium.click("name=__ant__D");
		selenium.click("name=__ant__B");
		selenium.click("name=__con__A");
		selenium.click("name=__con__E");
		selenium.click("css=button.btn");
		selenium.waitForPageToLoad("30000");
		selenium.click("link=Relational Model");
		selenium.click("link=FD Sets");
		selenium.waitForPageToLoad("30000");
		selenium.click("css=input[name=\"(B, D) -> (A, E)\"]");
		selenium.click("css=input[name=\"(A, B, C) -> (D, E)\"]");
		selenium.click("css=input[name=\"(A, D, E) -> (B)\"]");
		selenium.type("id=__fdjoint-name__", "Joint-1");
		selenium.click("css=button.btn");
		selenium.waitForPageToLoad("30000");
		selenium.type("id=__fdjoint-name__", "Joint-2");
		selenium.click("css=input[name=\"(A, D, E) -> (B)\"]");
		selenium.click("css=input[name=\"(B, D) -> (A, E)\"]");
		selenium.click("css=button.btn");
		selenium.waitForPageToLoad("30000");
		selenium.click("link=Relational Model");
		selenium.click("link=Relations");
		selenium.waitForPageToLoad("30000");
		selenium.type("id=__relation-name__", "R1");
		selenium.click("name=__fdjoint-name__");
		selenium.click("name=__attr__A");
		selenium.click("name=__attr__B");
		selenium.click("name=__attr__C");
		selenium.click("name=__attr__D");
		selenium.click("name=__attr__E");
		selenium.click("css=button.btn");
		selenium.waitForPageToLoad("30000");
		selenium.click("link=Tests");
		selenium.click("link=Normal Form");
		selenium.waitForPageToLoad("30000");
		selenium.click("name=__nf__");
		selenium.click("name=__relation-name__");
		selenium.click("css=button.btn");
		selenium.waitForPageToLoad("30000");
		selenium.click("xpath=(//input[@name='__nf__'])[3]");
		selenium.click("name=__relation-name__");
		selenium.click("css=button.btn");
		selenium.waitForPageToLoad("30000");
		selenium.click("xpath=(//input[@name='__nf__'])[4]");
		selenium.click("name=__relation-name__");
		selenium.click("css=button.btn");
		selenium.waitForPageToLoad("30000");
		selenium.click("link=Candidate/Super Keys");
		selenium.waitForPageToLoad("30000");
		selenium.click("name=__attr__B");
		selenium.click("name=__attr__C");
		selenium.click("name=__attr__D");
		selenium.click("name=__relation-name__");
		selenium.click("css=button.btn");
		selenium.waitForPageToLoad("30000");
		selenium.click("name=__attr__A");
		selenium.click("name=__relation-name__");
		selenium.click("css=button.btn");
		selenium.waitForPageToLoad("30000");
		selenium.click("name=__attr__E");
		selenium.click("name=__attr__D");
		selenium.click("name=__attr__C");
		selenium.click("name=__attr__B");
		selenium.click("name=__attr__A");
		selenium.click("name=__relation-name__");
		selenium.click("css=button.btn");
		selenium.waitForPageToLoad("30000");
		selenium.click("link=Tests");
		selenium.click("link=Minimal Cover");
		selenium.waitForPageToLoad("30000");
		selenium.click("name=__fdjoint-name__");
		selenium.click("css=button.btn");
		selenium.waitForPageToLoad("30000");
		selenium.click("xpath=(//input[@name='__fdjoint-name__'])[2]");
		selenium.click("css=button.btn");
		selenium.waitForPageToLoad("30000");
		selenium.click("link=Tests");
		selenium.click("link=FD Set A logically implies FD Set B");
		selenium.waitForPageToLoad("30000");
		selenium.click("name=__fdjoint-a__");
		selenium.click("xpath=(//input[@name='__fdjoint-b__'])[2]");
		selenium.click("css=button.btn");
		selenium.waitForPageToLoad("30000");
		selenium.click("xpath=(//input[@name='__fdjoint-a__'])[2]");
		selenium.click("name=__fdjoint-b__");
		selenium.click("css=button.btn");
		selenium.waitForPageToLoad("30000");
		selenium.click("link=Tests");
		selenium.click("link=Equivalence between two FD Sets");
		selenium.waitForPageToLoad("30000");
		selenium.click("name=__fdjoint-a__");
		selenium.click("name=__fdjoint-b__");
		selenium.click("css=button.btn");
		selenium.waitForPageToLoad("30000");
		selenium.click("name=__fdjoint-a__");
		selenium.click("xpath=(//input[@name='__fdjoint-b__'])[2]");
		selenium.click("link=Tests");
		selenium.click("link=Functional Dependency can be inferred from FD Set");
		selenium.waitForPageToLoad("30000");
		selenium.click("xpath=(//input[@name='__fd__'])[2]");
		selenium.click("name=__fdjoint-name__");
		selenium.click("css=button.btn");
		selenium.waitForPageToLoad("30000");
		selenium.click("xpath=(//input[@name='__fd__'])[2]");
		selenium.click("xpath=(//input[@name='__fdjoint-name__'])[2]");
		selenium.click("css=button.btn");
		selenium.waitForPageToLoad("30000");
		selenium.click("link=Analysis");
		selenium.click("link=Normalize");
		selenium.waitForPageToLoad("30000");
		selenium.click("name=__nf__");
		selenium.click("name=__relation-name__");
		selenium.click("css=button.btn");
		selenium.waitForPageToLoad("30000");
		selenium.click("xpath=(//input[@name='__nf__'])[2]");
		selenium.click("name=__relation-name__");
		selenium.click("css=button.btn");
		selenium.waitForPageToLoad("30000");
		selenium.click("link=Analysis");
		selenium.click("link=Project a FD Set on an Attribute Set");
		selenium.waitForPageToLoad("30000");
		selenium.click("name=__fdjoint-name__");
		selenium.click("name=__attr__B");
		selenium.click("name=__attr__D");
		selenium.click("name=__attr__E");
		selenium.click("name=__attr__A");
		selenium.click("css=button.btn");
		selenium.waitForPageToLoad("30000");
		selenium.click("xpath=(//input[@name='__fdjoint-name__'])[2]");
		selenium.click("name=__attr__B");
		selenium.click("name=__attr__D");
		selenium.click("css=button.btn");
		selenium.waitForPageToLoad("30000");
		selenium.click("link=Analysis");
		selenium.click("link=Attribute Set Closure");
		selenium.waitForPageToLoad("30000");
		selenium.click("name=__attr__A");
		selenium.click("name=__attr__B");
		selenium.click("name=__relation-name__");
		selenium.click("css=button.btn");
		selenium.waitForPageToLoad("30000");
		selenium.click("name=__attr__B");
		selenium.click("name=__attr__C");
		selenium.click("name=__attr__D");
		selenium.click("name=__relation-name__");
		selenium.click("css=button.btn");
		selenium.waitForPageToLoad("30000");
		selenium.click("link=Analysis");
		selenium.click("link=Calculate Minimal Cover");
		selenium.waitForPageToLoad("30000");
		selenium.click("name=__fdjoint-name__");
		selenium.click("css=button.btn");
		selenium.waitForPageToLoad("30000");
		selenium.click("xpath=(//input[@name='__fdjoint-name__'])[2]");
		selenium.click("css=button.btn");
		selenium.waitForPageToLoad("30000");
		selenium.click("link=Analysis");
		selenium.click("link=Calculate Candidate Keys");
		selenium.waitForPageToLoad("30000");
		selenium.click("name=__relation-name__");
		selenium.click("css=button.btn");
		selenium.waitForPageToLoad("30000");
	}

	@After
	public void tearDown() throws Exception {
		selenium.stop();
	}
}
